### ISSUE TITLE
MEGNetLayer edge output is not differentiable

### ISSUE THREAD

**Issue by wimwimyam** [materialsvirtuallab/megnet#20]
my model architecture is very simple, and I follow the code you provided in the section 'Customized Graph Network Models'. I only change out[2] to out[1] in order to get edge output. I got an error when I try to fit the model. 

code:

def keras_model():
    K.clear_session()
    n_atom_feature= 5
    n_bond_feature = 16
    n_global_feature = 1
    # Define model inputs
    int32 = 'int32'
    x1 = Input(shape=(None, n_atom_feature)) # atom feature placeholder
    x2 = Input(shape=(None, n_bond_feature)) # bond feature placeholder
    x3 = Input(shape=(None, n_global_feature)) # global feature placeholder
    x4 = Input(shape=(None,), dtype=int32) # bond index1 placeholder
    x5 = Input(shape=(None,), dtype=int32) # bond index2 placeholder
    x6 = Input(shape=(None,), dtype=int32) # atom_ind placeholder
    x7 = Input(shape=(None,), dtype=int32) # bond_ind placeholder
    xs = [x1, x2, x3, x4, x5, x6, x7]
    # Pass the inputs to the MEGNetLayer layer
    # Here the list are the hidden units + the output unit, 
    # you can have others like [n1] or [n1, n2, n3 ...] if you want. 
    out = MEGNetLayer([32, 16], [32, 16], [32, 16], pool_method='mean', activation='relu')(xs)
    # the output is a tuple of new graphs V, E and u
    # Since u is a per-structure quantity, 
    # we can directly use it to predict per-structure property
    out = Dense(1)(out[1])
    # Set up the model and compile it!
    model = Model(inputs=xs, outputs=out)
    model.compile(loss='mae', optimizer='adam')

error:

ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

Thanks.

**Comment by chc273** [comment]
@wimwimyam 

Hi, since all level of information will eventually pass through the state attributes, you will need to include state attributes (out[2]) somehow in the model outputs. Otherwise, some weights (in the state update substep in the last megnet layer) will have no gradients in the last graph layer, since backprop will not reach there. 

In original implementation, we reduce the atom and bond attributs to per structure vector and concatenate with state attributes after the final graph layer to enable information connection to all weights.

**Comment by Quetzalcohuatl** [comment]
@chc273 Can you point me to the example of the "original implementation"? Where can I see what your 'per structure vector' atom and bond attributes, and where can I see your state attributes? I am really confused, im trying but I just not fully understanding. The 'notebooks' folder doesn't have any examples of making a Customized Graph Network Models. =(

**Comment by chc273** [comment]
@Quetzalcohuatl 
oh that one is in "models.py". the function name is "make_megnet_model"

**Comment by Quetzalcohuatl** [comment]
@chc273 Hi , but I am just kind of confused on how to shape my stuffs... let's say I just want to predict bond distance given Node atomic numbers and bond types for the molecule H2O...it's confusing what I need to do :(

Like, i should have, N=3 atoms and M=2 bonds. So, how do I even know how to make V? it is NxNv in shape, but I don't know what lowercase v means... So maybe i assume v=1. Then to make a 3x3 matrix to create V, but already I don't even know how to represent this. I think maybe it looks like:

```
[[1,0,0],
[0,1,0],
[0,0,8]]
```
because index 0 is hydrogen has atomic number 1, and index 1 is hydrogen has atomic number 1, and index 2 is oxygen has atomic number 8.

because those are the atomic numbers. Then, to put the bond type, we know it is just single bonds which i will represent with a 1. So E is MxNm matrix, which in this case is 2x3. So, since vertex0 and vertex1 are both Hydrogens, there is no bond. There is only bond between the Oxygen (vertex2) and the hydrogens. So I should represent E like this:

```
[[1,0,1]
[[0,1,1]]
```
Because the first bond (the first row) is composed of index0 and index2, and the second bond (the second row) is composed of index1 and index2

because only hydrogens are the bonds, we can represent bond_index1 is

```
[0,1]
```

because only bond with oxygen (index 2) , bond_index2 is

```
[2,2]
```

because all atoms belong to the first structure, atom_ind is
```
[0,0]
```

because all bonds belong to the first structure, bond_ind is

```
[0,0]
```

Ugh, i just know this is so wrong :( It is hard for to understand . Where am i going wrong?

**Comment by wimwimyam** [comment]
@chc273 Thanks for your reply! The example can only due with structure vector output, how can we modify the code such that the model can have atom/bond attributes as our outputs? thanks!

**Comment by chc273** [comment]
Let's say you have H2O, the order of atoms are [H, H, O].

The atom attributes would be 3xNv, where Nv is the feature dimension space. You can choose, for example, atomic number and electronegativity as features, so for each atom you will have a vector of 2 as the atom feature. 

The atom feature matrix would be
```
[[1, 2.2],
[1, 2.2],
[8, 3.44]]
```

For the bond attributes, we build the bonds from the first atom to the last atom. There will be in total 4 bonds (double counting 0-1, 1-0, since it is an atom-by-atom bond building process). Let say the bond feature for each bond is a vector `[0, 0.1]`, the bond features will be

```
[[0, 0.1], 
[0, 0.1], 
[0, 0.1], 
[0, 0.1]]
```
with `index1` and `index2` being
`[0, 1, 2, 2]`, `[2, 2, 0, 1]`. This says that atom `index1[i]` and `index2[i]` form the bond `i`.

**Comment by chc273** [comment]
@Quetzalcohuatl 

When doing the real calculations, we will need to expand the first dimension and include atom index and bond index. These are described in `README.md`.

**Comment by chc273** [comment]
@wimwimyam  

A non-optimal solution would be taking out[2] (state vector), multiplying by 0 and adding it to out[0] to get the atom output, or adding it to out[1] to get the bond output. 

In this way, the model should be trainable. I have never tried though.
